name: flutter_fbx3d_viewer
description: Flutter package for viewing Fbx 3d animated files with textures, basic lights, colors.
version: 1.0.0
homepage: https://github.com/klaszlo8207/Flutter-FBX-3D-Viewer

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  vector_math: ^2.1.4
  provider: ^6.1.1
  archive: ^3.4.10
  image: ^4.1.7

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
    assets:
    - assets/

