name: flutter_fbx3d_viewer
description: Flutter package for viewing Fbx 3d animated files.
version: 0.0.2
homepage: https://github.com/klaszlo8207/Flutter-FBX-3D-Viewer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fbx: ^0.2.0
  vector_math: ^2.0.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
      # To add assets to your package, add an assets section, like this:
    assets:
    - assets/knight.fbx

