name: flutter_fbx3d_viewer
description: Flutter package for viewing Fbx 3d animated files. Now it is only a non textured version.
version: 0.0.2
homepage: https://github.com/klaszlo8207/Flutter-FBX-3D-Viewer

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  fbx: ^0.2.0
  vector_math: ^2.0.8

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
    assets:
    - assets/knight.fbx

